### ISSUE TITLE
Fix broken tilemaps

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#148]
I broke it and I'm too afraid to touch it again 😞 

<img width="347" alt="Screen Shot 2020-08-29 at 9 48 58 AM" src="https://user-images.githubusercontent.com/179544/91642020-ddb62480-e9dc-11ea-9f8e-48a2e4558ca7.png">

**Comment by MazurkaLFG** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/66224077/91662964-6ac7af00-eaab-11ea-972c-113f4c6cf5db.png)
