### ISSUE TITLE
Move the bedroom up relative to the camera to make room for the dialog box

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#175]
In the Bedroom scene, the DialogBox covers almost half the room when it's open. There's space to move the room up relative to the camera, so let's do it!

<img width="1137" alt="Screen Shot 2020-09-12 at 7 08 42 PM" src="https://user-images.githubusercontent.com/179544/93008603-64194d00-f52b-11ea-8ea4-5585a94ca934.png">

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/93022813-b9e40880-f5b0-11ea-8f0f-039b5045fb40.png)
