### ISSUE TITLE
Quest UI

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#182]
We need some kind of basic system for reviewing the quests assigned to Kay.

- [x] Art for quest log
- [x] Create new canvas layer with art
- [x] Maintain a list of quests
- [x] Fill in quest text in canvas
- [x] Trigger canvas with a keypress
- [x] Create function to add quests to log from Ink scripts
- [ ] Make quest list scrollable
- [x] Be able to navigate quest list items
- [x] Show quest detail panel
- [x] Implement Thomas' Birthday Breakfast (see issue #183 )

The simplest model that comes to mind is the one from Stardew Valley. Here's the quest log:

![S3bmtqa](https://user-images.githubusercontent.com/179544/93551907-f5216700-f923-11ea-8779-cb834adc72ff.jpg)

And here's a quest detail, with a back button to return to the log.

![bikzppumfpzy](https://user-images.githubusercontent.com/179544/93551921-ffdbfc00-f923-11ea-97bb-2603ebca1d06.jpg)

Here are some examples of how quests are given and accepted:

![svebeSp](https://user-images.githubusercontent.com/179544/93551961-184c1680-f924-11ea-84df-8d85ebe31825.jpg)

![DMyynpnUMAAzVPt](https://user-images.githubusercontent.com/179544/93552016-37e33f00-f924-11ea-8c6d-17717bafaabc.jpg)

And sometimes the game tells you you've received a quest, via a tooltip, and you just have to go into the quest log and read it.

**Comment by MazurkaLFG** [comment]
![ui_quest log example](https://user-images.githubusercontent.com/66224077/93723971-c3e5a880-fb68-11ea-9caa-e44b5e56d769.png)

A very basic layout that can be expanded upon.

**Comment by MazurkaLFG** [comment]
I'd really like to help get this going but I am not sure what else I can or should do next? If anyone has suggestions!

**Comment by MazurkaLFG** [comment]
We have this list of quests so far in the Tails of [Schala story document:](https://docs.google.com/document/d/1fzmMKI9zN4q7VUq7AuXMTQ8ZrnOiOusrsbhewdNwHf8/edit?usp=sharing)


**Quest Appendix**


Quest 1: Collect Materials for Birthday Breakfast
Quest 2: Fight Wheat Monster, earn wheat, Feed Goats
Quest 3: Go to town, talk to Blacksmith about picking up lantern
Quest 4: Lantern Repair Quest Chain
	Optional Side Quests: 
		Optional 1:The Fool has a quest for us to talk to her ancestor 200 years in 
		the past. What a crazy lady! 
Quest 5: Speak to Wizard to see how to return home
Quest 6: Speak to Warrior and receive training
	Warrior Quest Chains (Kill lots of baddies)
Quest 7: Speak to Cleric and receive training
	Cleric Quest Chains (Firefly quest!!)
Quest 8: Kill 3 main monsters - Water monster, Forest monster, Mountain Monster

**Comment by melanie** [comment]
We did it! Woo!
