### ISSUE TITLE
Mysterious collision in orchard

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#191]
<img width="515" alt="Screen Shot 2020-09-19 at 6 49 33 PM" src="https://user-images.githubusercontent.com/179544/93692498-fd56df00-faa8-11ea-9a3c-32c439e3bc52.png">

This spot has a weird collision - can someone figure out why?

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/94084058-3903e880-fdca-11ea-8dd8-cbb2b82e3904.png)
