### ISSUE TITLE
Main tree in town needs some layer help

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#192]
<img width="238" alt="Screen Shot 2020-09-19 at 6 51 59 PM" src="https://user-images.githubusercontent.com/179544/93692566-92f26e80-faa9-11ea-8a14-cf42f2a02158.png">

Collision and layer problems - please help!

**Comment by MazurkaLFG** [comment]
I'll work on this this week!

**Comment by MazurkaLFG** [comment]
Fixed! 

Added new tree sprites/animation for the bottom trees that were funky. 


https://www.loom.com/share/328a3453a55b441d87b0210f9e4ac5fa
