### ISSUE TITLE
Randomly Generated NPCs 

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#228]
During our last meeting, it was suggested that we have several versions of random NPCs to make the town feel more alive. They would not be interactable, and could even walk across the screen and disappear. Some suggestions for art:

- [ ] 3 different body sizes (small, medium, large) that could be swapped out
- [ ] Up to 8 variations of hairstyles, faces, clothing.
- [ ] Scripting that could randomize these features.

**Comment by melanie** [comment]
I'm thinking that it might actually be less work just make a zillion different `random_person` sprites, rather than try to figure out how to assemble and animate sprites from component parts programmatically...  but I'll do some thinkin' on it!
