### ISSUE TITLE
Quest Item Collectables Prefabs

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#233]
We already have these sprites in the world, just need to add the script and turn them into prefabs!

- [x] Add Collectable Script first quest items (rosemary, mushrooms, saffron) 
- [x] Turn those items into prefabs

**Comment by Druffl3** [comment]
Will this project run on a mac? I am thinking of picking it up, if it does.

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/95135999-f4ae0c00-072a-11eb-8bcf-8ba222fe56d6.png)
