### ISSUE TITLE
Apothecary Cat Script

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#252]
This apothecary cat looks so cute in so many places in the apothecary! Can we make a script so that every time we leave and re-enter the apothecary, it randomly generates to a new set location, maybe between 4 specified spots? 

(Cat sprite is already in the apothecary, fully animated)

![kitty_animation](https://user-images.githubusercontent.com/66224077/95661966-34913c80-0af9-11eb-8a60-b847a7222561.png)

**Comment by MazurkaLFG** [comment]
Great positions for the cat to go to:

Current: -1.13, .98

Alternates:
-1.13, -2.28
1.89, 2.42

**Comment by melanie** [comment]
Done!
