### ISSUE TITLE
Character Eyeballs

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#271]
Some of our characters could use bigger eyeballs. Here are some suggestions from other pixel art games:

Stardew Valley
![image](https://user-images.githubusercontent.com/66224077/96348118-ed142e80-106b-11eb-905b-9850f5b4b788.png)

![image](https://user-images.githubusercontent.com/66224077/96348135-146afb80-106c-11eb-8405-208455df25a9.png)

**Comment by melanie** [comment]
## Kay
<img width="426" alt="Screen_Shot_2020-10-17_at_11 15 54_AM" src="https://user-images.githubusercontent.com/179544/96350865-aecb3f00-106c-11eb-8f50-53074f1b6e6f.png">

## Mother
<img width="382" alt="Screen Shot 2020-10-17 at 11 06 22 AM" src="https://user-images.githubusercontent.com/179544/96350821-775c9280-106c-11eb-9aed-4380e7ebaf1f.png">

## Father
![Screen_Shot_2020-10-17_at_11 27 39_AM](https://user-images.githubusercontent.com/179544/96350869-b12d9900-106c-11eb-969e-0a24ced903c2.png)

## Thomas
<img width="683" alt="Screen Shot 2020-10-17 at 11 39 36 AM" src="https://user-images.githubusercontent.com/179544/96350978-7841f400-106d-11eb-9436-d912d75bba66.png">

**Comment by melanie** [comment]
## Inkeeper
Also shortened his arms a little.
<img width="723" alt="Screen Shot 2020-10-17 at 11 56 33 AM" src="https://user-images.githubusercontent.com/179544/96351406-e38cc580-106f-11eb-8567-acd800af7e58.png">

## Bar Wench
Also narrowed her shoulders a tad, and added some shading around the hairline.
<img width="446" alt="Screen Shot 2020-10-17 at 12 13 09 PM" src="https://user-images.githubusercontent.com/179544/96351721-31a2c880-1072-11eb-84ce-d6e88b375ea6.png">

## Bard 
<img width="835" alt="Screen Shot 2020-10-17 at 12 23 25 PM" src="https://user-images.githubusercontent.com/179544/96351886-914da380-1073-11eb-9c5c-9715e79772cc.png">

**Comment by melanie** [comment]
## Mayor
<img width="497" alt="Screen Shot 2020-10-17 at 12 37 56 PM" src="https://user-images.githubusercontent.com/179544/96352096-99a6de00-1075-11eb-9eba-d6e8fe8406da.png">

## Stinky Bumpkin
Not much to change here, just outlined in black and added a highlight to the eye white.
<img width="746" alt="Screen Shot 2020-10-17 at 12 43 12 PM" src="https://user-images.githubusercontent.com/179544/96352227-69137400-1076-11eb-8e9e-e7404fe9b733.png">

**Comment by MazurkaLFG** [comment]
Closing for now! Can revisit art touchups in a later issue!
