### ISSUE TITLE
Goat gates need open state

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#29]
In order to hook up a gate-open action, we need a frame of the gate open (I don't think it needs to be animated).

**Comment by MazurkaLFG** [comment]
Here we go! Open gate art. 

![open fence gate](https://user-images.githubusercontent.com/66224077/88439187-1f492380-cdd0-11ea-9575-4dff6bceaf96.png)

**Comment by MazurkaLFG** [comment]
Here are the spritesheets. 

![Goat Fence Gate Sprite Sheet](https://user-images.githubusercontent.com/66224077/88440596-11959d00-cdd4-11ea-955e-8728738635a9.png)
![open fence gate back sprite sheet](https://user-images.githubusercontent.com/66224077/88440597-11959d00-cdd4-11ea-908c-f1cee26e400d.png)
