### ISSUE TITLE
Medieval Town Square Pillory

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#309]
We won't have our giant tree in the center of town square, so let's put in some more medieval-ee things.
![image](https://user-images.githubusercontent.com/66224077/97927946-983f0c00-1d2b-11eb-91e5-e3da02cfd944.png)

- [x] Pillory
- [x] hangman's noose (or not I dunno just spitballin)
- [x] Wagons/different types of food stalls
- [x] Practice dummies
- [x] Practice archery bullseyes

Inspiration:

![image](https://user-images.githubusercontent.com/66224077/97928045-d0dee580-1d2b-11eb-8d3e-e282a44ad716.png)

![image](https://user-images.githubusercontent.com/66224077/97927893-7fcef180-1d2b-11eb-9c71-673eb8f6f973.png)

![image](https://user-images.githubusercontent.com/66224077/97928244-359a4000-1d2c-11eb-9fb8-25f7e143d640.png)

![image](https://user-images.githubusercontent.com/66224077/97928254-421e9880-1d2c-11eb-95fa-b9d359aa09b2.png)

**Comment by EricDovigi** [comment]
![pillory](https://user-images.githubusercontent.com/67932984/98042389-bd418680-1de0-11eb-9ea0-e04059cc6e58.png)
Here's a pillory. It's more of the crouch-down kind than the stand up kind in the sample photo

**Comment by EricDovigi** [comment]
![target](https://user-images.githubusercontent.com/67932984/98044058-828d1d80-1de3-11eb-9b55-1a85693a36b3.png)

**Comment by EricDovigi** [comment]
![target](https://user-images.githubusercontent.com/67932984/98044233-cbdd6d00-1de3-11eb-8bf6-181f8866aceb.png)

**Comment by EricDovigi** [comment]
![cart](https://user-images.githubusercontent.com/67932984/98186525-23ef9e80-1ecc-11eb-982f-ca83dad785fd.png)

**Comment by EricDovigi** [comment]
![gallows](https://user-images.githubusercontent.com/67932984/98433207-154ae800-2082-11eb-83d7-0432fc8b8b8e.png)
![Uploading platform.png…]()

**Comment by EricDovigi** [comment]
![platform](https://user-images.githubusercontent.com/67932984/98433211-1aa83280-2082-11eb-9215-605a8ad9259e.png)

**Comment by EricDovigi** [comment]
![target](https://user-images.githubusercontent.com/67932984/99119138-03070780-25b6-11eb-969e-452eb600160a.png)

**Comment by EricDovigi** [comment]
target dummy

**Comment by EricDovigi** [comment]
![target2](https://user-images.githubusercontent.com/67932984/99119689-d2739d80-25b6-11eb-9b68-a0e1f72f40ad.png)
