### ISSUE TITLE
Create a feedback form for the website

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#326]
When we send folks to our website to play the snapshot, it'd be great if we could collect some feedback. Could someone set up a Google Form or something?

**Comment by MazurkaLFG** [comment]
I'm pretty well versed in google forming! What are some of the topics we should be asking about? A quick google search brought this up:

The goal of post-playtest questions is to get unadulterated feelings from the person. You do not want to lead them in any way, but you want to find out what they thought. Try these questions:

What was the most frustrating moment or aspect of what you just played?
What was your favorite moment or aspect of what you just played?
Was there anything you wanted to do that you couldn’t?
If you had a magic wand to wave, and you could change, add, or remove anything from the experience, what would it be?
What were you doing in the experience?
How would you describe this game to your friends and family?

The easy to remember (though ridiculous) mnemonic is ffwwdd:

Frustrating Favorite Wanted Wand Doing Describe

**Comment by melanie** [comment]
I think the fewer form questions, the more likely people are to fill it out - maybe for now, just the first two questions would be good? And maybe an extra field for just whatever they want to say?

I'm also thinking that we might use this form to log bugs when playtesting, too.

**Comment by MazurkaLFG** [comment]
Form: https://forms.gle/A2vTXJ1HJfDm7vZT8

HTML:

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeeeZ87I6OxAASn96zrr2cuAmBAQ3FoeCSRipRDz_QZfz6G3g/viewform?embedded=true" width="640" height="825" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by MazurkaLFG** [comment]
Let me know if you think there should be any changes or if you need something else to put on the website @melanie

**Comment by melanie** [comment]
The form looks great - I added a big "Tell us what you think!" button to the site!
