### ISSUE TITLE
Chickens

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#36]
We need chicken sprites!! They should move around, but don't need to be too complicated. They can just move left and right. They need a sound!

- [ ] A few chickens (and chicks) with walking animations
- [ ] Chicken coop
- [ ] Cluck noises
- [ ] Insert in farm scene

**Comment by AdamGEmerson** [comment]
Code for the Goats can be easily added to the chickens once we have the sprites.

**Comment by melanie** [comment]
Closing this as it's covered in #283
