### ISSUE TITLE
Wheat!

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#38]
We could use some improved wheat tiles, as well as some animations for when they're struck with the scythe.

**Comment by MazurkaLFG** [comment]
I didn't make new wheat but I added a bunch more of it to the scene, looks a little better I think. Will close for now, we can come fix it up later if needed.

![image](https://user-images.githubusercontent.com/66224077/88742754-9819e980-d108-11ea-84fc-1a6c07edc890.png)

**Comment by MazurkaLFG** [comment]
![goat feeder sprite sheet](https://user-images.githubusercontent.com/66224077/93261240-10e00e00-f768-11ea-9337-6cabe32d0433.png)
![wheat_new](https://user-images.githubusercontent.com/66224077/93261290-1fc6c080-f768-11ea-8791-380ebdd3f06e.png)
