### ISSUE TITLE
School

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#43]
- [x] Pixel art for building exterior (Krisy)
- [x] Add to Town scene
- [x] Insert Teacher character (see issue #66 )

**Comment by MazurkaLFG** [comment]
![old man](https://user-images.githubusercontent.com/66224077/88621423-0a85bd80-d066-11ea-8e6a-541da1b25580.png)
![professor](https://user-images.githubusercontent.com/66224077/88621424-0a85bd80-d066-11ea-9c2c-a1c1c07253c9.png)

We'll decide which one we want for the professor.
