### ISSUE TITLE
Church/Cathedral

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#44]
- [x] Building exterior
- [x] Gravestones in graveyard
- [x] Add to Town scene

[](url) https://github.com/SolidGoldStudios/TailsOfSchala/issues/67#issue-661243592

**Comment by MazurkaLFG** [comment]
![Grave 1](https://user-images.githubusercontent.com/66224077/88438027-5b2eb980-cdcd-11ea-9c70-8adad50be1b5.png)
![Grave 2](https://user-images.githubusercontent.com/66224077/88438029-5bc75000-cdcd-11ea-8727-57ccd79bb11e.png)
![Grave 3](https://user-images.githubusercontent.com/66224077/88438030-5bc75000-cdcd-11ea-9e2b-5d593423ef68.png)
![Grave 4](https://user-images.githubusercontent.com/66224077/88438031-5bc75000-cdcd-11ea-8cf8-ffecbacf2322.png)
![Grave 5](https://user-images.githubusercontent.com/66224077/88438032-5c5fe680-cdcd-11ea-9a5e-5b1f2a7d6ebd.png)
![Grave 6](https://user-images.githubusercontent.com/66224077/88438034-5c5fe680-cdcd-11ea-90ab-7f2ab1dd8916.png)
