### ISSUE TITLE
Inn/Tavern

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#45]
- [x] Tavern building exterior
- [ ] Tavern building interior
- [x] Innkeeper character (see issue #32)
- [x] Add exterior to town scene
- [ ] Add interior scene
- [x] Tavern music
- [ ] Add Eric's tavern music to interior scene

**Comment by MazurkaLFG** [comment]
![tavern](https://user-images.githubusercontent.com/66224077/89001135-e244cb80-d2be-11ea-9590-938794534c1b.png)
