### ISSUE TITLE
Train & Tracks

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#46]
Need some train-track tiles, and maybe a train!

**Comment by MazurkaLFG** [comment]
![train](https://user-images.githubusercontent.com/66224077/94354421-6e197080-0040-11eb-8a1e-a86a1ec76b9a.png)
![trainstation](https://user-images.githubusercontent.com/66224077/94354424-770a4200-0040-11eb-99ae-29f4d63e1aa1.png)
![traintracks](https://user-images.githubusercontent.com/66224077/94354426-77a2d880-0040-11eb-9435-609494c048f5.png)
