### ISSUE TITLE
Horses & Carriages

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#48]
Draw some horses and carriages! Animations would be nice too, if only a tail-swish for the horses.

- [x] Pixel art
- [x] Add to Town scene

**Comment by MazurkaLFG** [comment]
![stables with horses](https://user-images.githubusercontent.com/66224077/88864320-88fb7000-d1ca-11ea-9577-14ee60f2697b.png)
![derpy horse](https://user-images.githubusercontent.com/66224077/88864403-b9dba500-d1ca-11ea-8616-8ccfb71df894.png)

**Comment by MazurkaLFG** [comment]
![horse with carriage](https://user-images.githubusercontent.com/66224077/90302301-d33b4d00-de6a-11ea-896f-1ca7f60a3805.png)
