### ISSUE TITLE
Cathedral Song/Antagonist Theme

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#58]

**Comment by MazurkaLFG** [comment]
Maybe not quite an antagonist theme, but I had cathedral music in mind when making it. This is the first draft, I've asked Jesse if he would be interested in collaborating on it and adding some more sounds. I could also see this being the portal song/in between worlds song. 

[](url) https://drive.google.com/file/d/1wKsN69TzXeHH-H2c_n9UEB0v83ypspxG/view?usp=sharing

**Comment by ploppowaffles** [comment]
Very cool and haunting!  Feels like a creepy ancient cathedral.

**Comment by MazurkaLFG** [comment]
Still need an Antagonist "Theme" but this would be a good cathedral song.
