### ISSUE TITLE
Quest #2: Go to town and get an item for Mother

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#59]
Our second quest, which will take our character to town! We'll need:

- [x] Quest dialog
- [x] The path-to-town scene completed
- [x] Apothecary shop exterior
- [x] Apothecary shop interior
- [x] Apothecary character _(see issue #33 or Google Drive for the sprite)_
- [x] Apothecary shop music (see issue #57 )
- [x] The item you need to pick up (art and writing)

**Comment by EricDovigi** [comment]
@MazurkaLFG Good idea, I'll work on that. I might need some help brainstorming possible branches and options in that first bit of dialogue

**Comment by MazurkaLFG** [comment]
Some inspiration for the lantern:

![1800s bicycle lantern](https://user-images.githubusercontent.com/66224077/89128962-dde70100-d4be-11ea-97ad-e21b923e57b8.png)

**Comment by MazurkaLFG** [comment]
![Lantern_Inventory](https://user-images.githubusercontent.com/66224077/94355108-be93cc80-0046-11eb-8567-725ae641e492.png)
