### ISSUE TITLE
Mother character

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#63]
- [x] Concept art
- [x] Pixel art 
- [x] Add to house scene

**Comment by MazurkaLFG** [comment]
I'll plop her in there right now!

**Comment by melanie** [comment]
Kevin's concept art and inspiration!

![mother_1880_s](https://user-images.githubusercontent.com/179544/87890668-48427080-c9ec-11ea-8acc-03f524f89b68.jpg)
![Mother_1880_s_inspiration](https://user-images.githubusercontent.com/179544/87890670-4a0c3400-c9ec-11ea-9958-e5fb5d5b975a.jpg)

**Comment by melanie** [comment]
Krisy's sprite (also on the Google Drive!)

![Mother Sprite](https://user-images.githubusercontent.com/179544/87890704-64461200-c9ec-11ea-9772-3d715126f83f.png)
