### ISSUE TITLE
Evil Priest character

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#67]
- [x] Character development
- [x] Concept art
- [x] Pixel art

**Comment by melanie** [comment]
Character development:
https://docs.google.com/document/d/1CdKaVBhDIhbKqqeV8sF_ZBr6dxS7lTo5l6v005qzhgw/edit#heading=h.89gsmp1918be

**Comment by melanie** [comment]
Kevin's concept art and inspiration:

![priest_1880s](https://user-images.githubusercontent.com/179544/87891289-4da0ba80-c9ee-11ea-8730-77ad41888cdb.jpg)
![priest_1880s_inspiration](https://user-images.githubusercontent.com/179544/87891291-4f6a7e00-c9ee-11ea-9f4b-a640b7480665.jpg)

**Comment by MazurkaLFG** [comment]
I'm sure he has a lovely personality. 
![priest](https://user-images.githubusercontent.com/66224077/88005745-a6944f80-cacf-11ea-8f37-f50921368c3e.png)
