### ISSUE TITLE
Fool character

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#68]
- [x] Character development
- [x] Concept art
- [x] Pixel art
- [x] Add to the town scene somewhere
- [x] Will she have dialog? Offering some "sorrowful wisdom?"

**Comment by melanie** [comment]
Character development!

https://docs.google.com/document/d/1CdKaVBhDIhbKqqeV8sF_ZBr6dxS7lTo5l6v005qzhgw/edit#heading=h.89gsmp1918be

**Comment by melanie** [comment]
Concept art and inspiration:

![fool_1880_s](https://user-images.githubusercontent.com/179544/87891492-f8b17400-c9ee-11ea-8604-7d785e310ab7.jpg)
![fool_1880s_inspiration](https://user-images.githubusercontent.com/179544/87891495-fa7b3780-c9ee-11ea-892d-71942c390248.jpg)

**Comment by MazurkaLFG** [comment]
![the fool](https://user-images.githubusercontent.com/66224077/88620901-c0500c80-d064-11ea-8b7d-d5f749a5c404.png)

**Comment by MazurkaLFG** [comment]
@EricDovigi - this one is almost ready to be completed, just need some dialogue examples from her! :)

**Comment by EricDovigi** [comment]
I posted the inky I made for the Fool ...somewhere... lol.

**Comment by EricDovigi** [comment]
Ah okay just put it in the branching dialogue folder here on github.
