### ISSUE TITLE
Refine character entry & exit points

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/TailsOfSchala#79]

**Comment by melanie** [comment]
I'm following this guide... hope it works!
https://medium.com/@johnathanmiller/scene-based-player-positioning-in-unity-4499f25e0521

**Comment by MazurkaLFG** [comment]
Can this one be closed? Seems pretty refined to me!

**Comment by melanie** [comment]
@MazurkaLFG Hell yeah!!
