### ISSUE TITLE
Road to farm scene

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#82]
For when we come back from town on the way back to the farm:
- [ ] Ability to use lantern here
- [x] lamp posts lit up.
- [x] Updated Landscape for Sunset (See Issue #81 )
- [x] Fix camera clamp.

**Comment by melanie** [comment]
@MazurkaLFG should we call this one finished, and maybe start up a new issue for general equipped items (i.e., the lantern?)
