### ISSUE TITLE
Home/Breakfast Scene Music

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#84]
We need a lovely song for our home scene interactions with the family.

**Comment by EricDovigi** [comment]
Let me see what I can whip up...

**Comment by EricDovigi** [comment]
[Morning Song.mp3.zip](https://github.com/SolidGoldStudios/TailsOfSchala/files/4983408/Morning.Song.mp3.zip)

**Comment by EricDovigi** [comment]
Here is a possible song for the morning
