### ISSUE TITLE
New NPC Creations

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#86]
Can we get a couple of other characters/their descriptions/concept art for the town scene?

**Troubadour/Bard:** 
- [x] Character Description/Dialogue (Eric)
- [x] Concept Art (Kevin)
- [x] Pixel Art (Krisy)

**Homeless Person**
- [x] Character Description/Dialogue (Eric)
- [x] Concept Art (Kevin)
- [ ] Pixel Art (Krisy)

**Coach Driver**
- [x] Character Description/Dialogue (Eric)
- [x] Concept Art (Kevin)
- [x] Pixel Art (Krisy)

**Town Guards x2**
- [x] Character Description/Dialogue (Eric)
- [x] Concept Art (Kevin)
- [x] Pixel Art (Krisy)

**Comment by EricDovigi** [comment]
I added descriptions for these characters to the Character Outline Google doc

https://docs.google.com/document/d/1CdKaVBhDIhbKqqeV8sF_ZBr6dxS7lTo5l6v005qzhgw/edit#
