### ISSUE TITLE
Blacksmith Exterior Items

### ISSUE THREAD

**Issue by MazurkaLFG** [SolidGoldStudios/TailsOfSchala#95]
Here's the layout of the Blacksmith that I've been working on. It could use lots of built in items near the fireplace. I'm not good at those :) Feel free to edit any of the other parts as well! 

Suggestions: 

- [x] Anvil
- [x] Carriage Wheel
- [x] Tools/Supplies
- [x] Workbench

![new blacksmith](https://user-images.githubusercontent.com/66224077/89077767-98a0c300-d348-11ea-9d6d-a932df3f096d.png)

**Comment by EricDovigi** [comment]
![blacksmith accoutrements](https://user-images.githubusercontent.com/67932984/89215543-b3a84880-d57d-11ea-9076-58c27c12dcd5.png)
